package com.sports.model.enums;

/**
 * Certificate Types
 */
public enum CertificateType {
    COACHING_CERTIFICATION,
    REFEREE_CERTIFICATION,
    PLAYER_ACHIEVEMENT,
    TOURNAMENT_WINNER,
    TOURNAMENT_RUNNER_UP,
    BEST_PLAYER_AWARD,
    PARTICIPATION_CERTIFICATE,
    TRAINING_CERTIFICATE,
    SPORTS_DEGREE,
    FITNESS_CERTIFICATION,
    MEDICAL_CLEARANCE,
    OTHER
}
